<?php
/*
 * Copyright (c) 2017-2025 Aimy Extensions, Netzum Sorglos Software GmbH
 * Copyright (c) 2015-2017 Aimy Extensions, Lingua-Systems Software GmbH
 *
 * https://www.aimy-extensions.com/
 *
 * License: GNU GPLv2, see LICENSE.txt within distribution and/or
 *          https://www.aimy-extensions.com/software-license.html
 */
 defined( '_JEXEC' ) or die(); use Joomla\CMS\Plugin\CMSPlugin; use Joomla\CMS\Factory; use Joomla\CMS\Language\Text; use Joomla\CMS\Uri\Uri; use Joomla\CMS\HTML\HTMLHelper; class plgSystemAimyH1Heading extends CMSPlugin { const SCOPE_PAGE = 1; const SCOPE_COMP = 2; private $skip = false; public function onAfterDispatch() { if ( ! self::in_frontend() ) { return; } $doc = Factory::getDocument(); if ( $doc->getType() !== 'html' ) { $this->skip = true; return; } $app = Factory::getApplication(); $ctx = $app->input->get( 'option', '', 'cmd' ) . '.' . $app->input->get( 'view', '', 'cmd' ); if ( $this->params->get( 'show_context', false ) ) { $lang = Factory::getLanguage(); $lang->load( 'plg_system_aimyh1heading', JPATH_ADMINISTRATOR ); $app->enqueueMessage( '<b>Aimy H1 Heading</b>: ' . Text::_( 'AIMY_H1_CONTEXT' ) . ': ' . '<code>' . $ctx . '</code>', 'notice' ); } if ( $this->params->get( 'check_count', false ) ) { HTMLHelper::_( 'jquery.framework' ); $doc->addScriptDeclaration( "jQuery(document).ready(function()" . "{" . "if ( jQuery( 'h1' ).length > 1 )" . "{" . "jQuery( 'h1' )" . ".css({" . "color: '#800'," . "textDecoration: 'underline'" . "})" . ".animate(" . "{" . "opacity: 0.85," . "fontSize: '4em'," . "marginTop: '+=1em'," . "marginBottom: '+=1em'" . "}," . "1500" . ")" . ";" . "}" . '});' ); } $eps = explode( "\r\n", $this->params->get( 'exclude_contexts', '' ) ); foreach ( $eps as $ep ) { $ep = trim( $ep ); if ( empty( $ep ) or strpos( $ep, '#' ) === 0 ) { continue; } if ( fnmatch( $ep, $ctx ) ) { $this->skip = true; return; } } if ( $this->params->get( 'scope', self::SCOPE_COMP ) == self::SCOPE_COMP ) { $buf = $doc->getBuffer( 'component', null, null ); if ( ! is_string( $buf ) or empty( $buf ) ) { return; } if ( self::upgrade_first_h2( $buf ) ) { $doc->setBuffer( $buf, array( 'type' => 'component', 'name' => null, 'title' => null ) ); } } } public function onAfterRender() { if ( ! self::in_frontend() or $this->skip or $this->params->get( 'scope', self::SCOPE_COMP ) != self::SCOPE_PAGE ) { return; } $app = Factory::getApplication(); $body = $app->getBody(); if ( ! is_string( $body ) or empty( $body ) ) { return; } if ( self::upgrade_first_h2( $body ) ) { $app->setBody( $body ); } } static private function upgrade_first_h2( &$s ) { if ( preg_match( '#<h1[^>]*>#i', $s ) ) { return false; } $m = array(); if ( ! preg_match( '#<h2(\s+[^>]*)?>(.*?)</h2>#si', $s, $m ) ) { return false; } $s = str_replace( $m[ 0 ], sprintf( '<h1%s>%s</h1>', $m[ 1 ], trim( $m[ 2 ] ) ), $s ); return true; } static private function in_frontend() { $app = Factory::getApplication(); if ( strpos( strVal( JVERSION ), '3.' ) === 0 ) { return $app->isSite(); } return $app->isClient( 'site' ); } } 
